/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/python-8be4a2579dd84586b915068e475073ee
Title: Python
*/

import {Float, useGLTF } from '@react-three/drei'

const PythonLogo = (props) => {
  const { nodes, materials } = useGLTF('models/python.glb')
  return (
    <Float floatIntensity={3}>
    <group  {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Python_Python_0.geometry}
          material={materials.Python}
          position={[7, 1.079, 0.181]}
          rotation={[-Math.PI / 2, 5, 0]}
          scale={[3.392, 4.392, 3.527]}
        />
      </group>
    </group>
    </Float>
  )
}

useGLTF.preload('models/python.glb');

export default PythonLogo;
